apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "provisioning-agent.fullname" . }}
  labels:
    {{- include "provisioning-agent.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "provisioning-agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "provisioning-agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "provisioning-agent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "provisioning-agent.fullname" . }}-config
                  key: LOG_LEVEL
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "provisioning-agent.fullname" . }}-config
                  key: OTEL_EXPORTER_OTLP_ENDPOINT
            - name: EDC_CONTROL_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "provisioning-agent.fullname" . }}-config
                  key: EDC_CONTROL_URL
            - name: EDC_MANAGEMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "provisioning-agent.fullname" . }}-config
                  key: EDC_MANAGEMENT_URL
            - name: KEYCLOAK_ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "provisioning-agent.fullname" . }}-config
                  key: KEYCLOAK_ADMIN_URL
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.vaultSecretName }}
                  key: VAULT_ADDR
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.vaultSecretName }}
                  key: VAULT_TOKEN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.keycloakAdminSecretName }}
                  key: ADMIN_PASSWORD
            - name: KEYCLOAK_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.keycloakAdminSecretName }}
                  key: ADMIN_USER
            - name: EDC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.edcApiKeySecretName }}
                  key: API_KEY
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
