"""
Task queue name constants.
Each worker group polls one queue. All workers on the same queue
MUST register the same workflow and activity types.
"""
from dataspace_control_plane_procedures._shared.task_queues import (
    COMPLIANCE_QUEUE,
    CONTRACTS_NEGOTIATION_QUEUE,
    MACHINE_TRUST_QUEUE,
    MAINTENANCE_QUEUE,
    ONBOARDING_QUEUE,
    TWINS_PUBLICATION_QUEUE,
)

ONBOARDING = ONBOARDING_QUEUE
MACHINE_TRUST = MACHINE_TRUST_QUEUE
TWINS_PUBLICATION = TWINS_PUBLICATION_QUEUE
CONTRACTS_NEGOTIATION = CONTRACTS_NEGOTIATION_QUEUE
COMPLIANCE = COMPLIANCE_QUEUE
MAINTENANCE = MAINTENANCE_QUEUE

ALL_QUEUES = [
    ONBOARDING,
    MACHINE_TRUST,
    TWINS_PUBLICATION,
    CONTRACTS_NEGOTIATION,
    COMPLIANCE,
    MAINTENANCE,
]
