extensions:
  # NEVER enable in staging or production
  pprof:
    endpoint: localhost:1777
    block_profile_fraction: 0
    mutex_profile_fraction: 0

  zpages:
    endpoint: localhost:55679

exporters:
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
service:
  extensions: [health_check, memory_ballast, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite, debug]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [loki, debug]
  telemetry:
    logs:
      level: debug
