service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource, k8sattributes, redaction, batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, resource, k8sattributes, batch]
      exporters: [prometheusremotewrite]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource, k8sattributes, redaction, batch]
      exporters: [loki]
